language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 17762375-6c66-4ba2-a6a6-82ca2f3de6bc
    app: rocky-retreat-21995
  on:
    repo: jgmil/node-shopping-list-integration-tests
